# This is  Thoth's configuration file placed in a root of a repo
# (named as .thoth.yaml) used by Thamos CLI as well as by Thoth bots. Please
# adjust values listed below as desired.

# A remote Thoth service to talk to:
host: khemenu.thoth-station.ninja

# Configure TLS verification for communication with remote Thoth instance:
tls_verify: true

# Format of requirements file, supported are "pip" and "pipenv":
requirements_format: pipenv

runtime_environments:
  - name: rhel8
    # Operating system for which the recommendations should be created:
    operating_system:
      name: rhel
      version: "8.0"
    # Labels to be used during the resolution (key-value pairs).
    labels:
    # Recommendation type - one of:
    #  * testing
    #  * stable
    #  * latest
    #  * performance
    #  * security
    # See https://thoth-station.ninja/recommendation-types/
    recommendation_type: latest

#
# Configuration of bots:
#
managers:
  - name: pipfile-requirements
  - name: info
  - name: version
    configuration:
      # A list of maintainers (GitHub or GitLab accounts) of this repository:
      maintainers:
        - codificat
        - goern
        - fridex
        - mayacostantini
      # A list of assignees to which the opened pull requests and issues should
      # be assigned to:
      assignees:
        - sesheta
      # Labels for issues and pull requests:
      labels:
        - bot
      # Automatically maintain a changelog file stating features of new
      # releases:
      changelog_file: true
      # Use AI/ML to group messages in a smart way.
      changelog_smart: true
  - name: update
    configuration:
      labels: [bot]
