host: khemenu.thoth-station.ninja
tls_verify: true
requirements_format: pipenv

runtime_environments:
  - name: rhel8
    operating_system:
      name: rhel
      version: "8.0"
    python_version: "3.8"
    recommendation_type: latest

managers:
  - name: pipfile-requirements
  - name: info
  - name: version
    configuration:
      assignees:
        - sesheta
      labels:
        - bot
      changelog_file: true
  - name: update
    configuration:
      labels: [bot]
